import{S as f,a as E,i as I}from"./assets/vendor-bad0427b.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function t(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerpolicy&&(a.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?a.credentials="include":r.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(r){if(r.ep)return;r.ep=!0;const a=t(r);fetch(r.href,a)}})();const w="https://pixabay.com/api/",P="41701983-23ca5d5908e2c78927e8095f2",d=40,L=new f(".gallery-item"),B=()=>{const e=new URL(w);return e.searchParams.append("key",P),e.searchParams.append("image_type","photo"),e.searchParams.append("orientation","horizontal"),e.searchParams.append("safesearch",!0),e},m=async(e,n=1)=>{try{const t=B();return t.searchParams.append("q",e),t.searchParams.append("page",n),t.searchParams.append("per_page",d),(await E.get(t.toString())).data.hits}catch(t){throw console.error("Error fetching images:",t),t}},g=e=>{const n=document.getElementById("gallery");n.innerHTML="",e.forEach(t=>{const{webformatURL:o,largeImageURL:r,tags:a,likes:i,views:h,comments:p,downloads:y}=t;n.insertAdjacentHTML("beforeend",`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${o}" alt="${a}"/>
      </a>
      <div class="image-info">
        <p>Likes: ${i}</p>
        <p>Views: ${h}</p>
        <p>Comments: ${p}</p>
        <p>Downloads: ${y}</p>
      </div>
    </li>
    `)}),L.refresh()},u=()=>{document.getElementById("loader").style.display="block"},c=()=>{document.getElementById("loader").style.display="none"},s=(e,n="info")=>{I[n]({title:e,position:"topCenter"})},b=async e=>{e.preventDefault();const t=document.getElementById("search-input").value.trim();if(t.length<3){s("Please enter a search query with at least 3 characters","warning");return}u();try{const o=await m(t);c(),o.length>0?(g(o),document.getElementById("load-more").style.display=o.length>=d?"block":"none"):s("Sorry, there are no images matching your search query. Please try again.","error")}catch{c(),s("Error fetching images. Please try again later.","error")}},v=async()=>{const n=document.getElementById("search-input").value.trim();if(n.length<3){s("Please enter a search query with at least 3 characters","warning");return}u();try{const t=await m(n,l);c(),t.length>0?(g(t),l++,window.scrollBy(0,S())):(s("No more images t load","info"),document.getElementById("load-more").style.display="none")}catch{c(),s("Error fetching images. Please try again later.","error")}},S=()=>{const e=document.querySelector(".gallery-item");return e?e.getBoundingClientRect().height:0};let l=1;const q=document.getElementById("form");q.addEventListener("submit",b);const M=document.getElementById("load-more");M.addEventListener("click",v);
//# sourceMappingURL=commonHelpers.js.map
